[build]
builder = "nixpacks"
installCommand = "npm install --legacy-peer-deps"

[phases.setup]
nixPkgs = ["...", "google-chrome-stable"]

[phases.install]
dependsOn = ["setup"]
cmds = ["npm install --legacy-peer-deps"]

[phases.build]
dependsOn = ["install"]
cmds = ["npm run build"]
